### ISSUE TITLE
Split document on theory and practical parts for each question

### ISSUE THREAD

**Issue by ufocoder** [ufocoder/javascript.interview#6]
Split document on theory and practical parts for each question.

For example:

Part of markdown before refactoring:
```
Hoisting in JavaScript:
* What is hoisting in JavaScript
* What will output the following code and why?
* What will output the following code and why?
* What will output the following code and why?
```

The same part of markdown refactoring after:

```
Hoisting in JavaScript:
* Theory:
  - What is hoisting in JavaScript
* Practice:
 - Example of code 1
 - Example of code 2
 - Example of code 3
```

**Comment by ermasavior** [comment]
hi. i'd like to take this

**Comment by ufocoder** [comment]
@rhaerma Cool! But keep in mind that some question have theory part either practical part

**Comment by ermasavior** [comment]
yes. where should we categorize such questions? should we create `Theory & Practice` part?
